httpEngine:
  port: 8088
  host: localhost

db:
  mysql:
    Address: localhost:3306
    User: blogAdmin
    Password: 20011717
    Database: blog
    TablePrefix: blog_

app:
  page_size: 10
  jwt_secret: 123456


redis:
  Host: 127.0.0.1:6379
