basePath: /api/v1
info:
  contact: { }
  description: This is a sample server celler server.
  title: Gin Gorm API
  version: "1.0"
paths:
  /api/v1/articles:
    get:
      description: 获取多篇文章
      parameters:
      - description: 标签ID
        in: query
        name: tag_id
        type: integer
      - description: 状态
        in: query
        name: state
        type: integer
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: Get multiple articles
      tags:
      - 文章
    post:
      description: 添加文章
      parameters:
        - description: 标签ID
          in: query
          name: tag_id
          required: true
          type: integer
        - description: 标题
          in: query
          name: title
          required: true
          type: string
        - description: 描述
          in: query
          name: desc
          required: true
          type: string
        - description: 内容
          in: query
          name: content
          required: true
          type: string
        - description: 创建人
          in: query
          name: created_by
          required: true
          type: string
        - description: 状态
          in: query
          name: state
          required: true
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: Add a article
      tags:
      - 文章
  /api/v1/articles/{id}:
    delete:
      consumes:
      - application/json
      description: 删除文章
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: Delete a article
      tags:
      - 文章
    get:
      description: 获取文章
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: Get a single article
      tags:
      - 文章
    put:
      description: 更新文章
      parameters:
        - description: ID
          in: path
          name: id
          required: true
          type: integer
        - description: 标签ID
          in: query
          name: tag_id
          required: true
          type: integer
        - description: 标题
          in: query
          name: title
          required: true
          type: string
        - description: 描述
          in: query
          name: desc
          required: true
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: Update a article
      tags:
      - 文章
  /api/v1/tags:
    get:
      description: Get multiple article tags
      parameters:
      - description: 标签名称
        in: query
        name: name
        type: string
      - description: 状态
        in: query
        name: state
        type: integer
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: GetTags
    post:
      description: Add multiple article tags
      parameters:
      - description: 标签名称
        in: query
        name: name
        required: true
        type: string
      - description: 状态
        in: query
        name: state
        type: integer
      - description: 创建人
        in: query
        name: created_by
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: AddTags
  /api/v1/tags/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: DeleteTags
    put:
      description: Edit multiple article tags
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: 标签名称
        in: query
        name: name
        required: true
        type: string
      - description: 状态
        in: query
        name: state
        type: integer
      - description: 修改人
        in: query
        name: modified_by
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: EditTags
  /auth:
    get:
      consumes:
      - application/json
      description: 获取用户信息
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - auth
swagger: "2.0"
